### PR TITLE
Added BedrockClans support

### PR DESCRIPTION
**Pull request by Wertzui123**
This pr adds bedrockclans support to purechat. The latest changes aren't tested, but the core works.

### CODE REVIEW

**Comment by supercrafti-lab** [comment]
How do I set it before the game name of the clan name?

**Comment by Wertzui123** [comment]
> How do I set it before the game name of the clan name?
You can use {clanname} for the name of the clan of the player.

**Comment by supercrafti** [comment]
dankesehr

**Comment by supercrafti** [comment]
wie kommt mal nochmal zu dem purechat zweig, von ihnen? ICH HABE EIN NEUES GERÄT, UND BENÖTIGE ES WIEDER. sorry für caps

**Comment by Wertzui123** [comment]
https://github.com/Wertzui123/PureChat

**Comment by supercrafti** [comment]
Ich habe vor den namen einer gruppe {Clanname} gemacht aber im chat wird alles wie normal angezeit, nur halt das "
{Clanname}" wie in der config davor steht

**Comment by Wertzui123** [comment]
It's {clan_name}. You also have to update your config.

**Comment by MrNinja008** [comment]
@SOF3  pls merge this :3

**Comment by SOF3** [comment]
I don't think we plan to maintain this anymore...

**Comment by Vecnavium** [comment]
And to add on to what SOFe has said, this is outdated code & Conflicts are caused, please resolve and be sure BedrockClans addon works on API 4.0.0.

**Comment by Wertzui123** [comment]
> be sure BedrockClans addon works on API 4.0.0

Are there addons for PureChat on PocketMine 4?

**Comment by Vecnavium** [comment]
At this moment no, all was removed from PureChat

**Comment by SOF3** [comment]
Use InfoAPI, then no addon needed ^_^

**Pull request closed without merging**
